### ISSUE TITLE
Unsupported Double-quoted on attribute_min/max method for MySQL

### ISSUE THREAD

**Issue by denmarkmeralpis** [neume/queryko#1]
Double-qouted issue when using MySQL

```ruby
...
relation.where("\"#{defined_table_name}\".\"#{column_name}\" >= ?", params[key.to_sym])
...
```
I'm using the gem version `1.1.3`

**Comment by neume** [comment]
Fixed the issue in version `1.1.4`. Please update your gem accordingly
You can check the commit [here](https://github.com/neume/queryko/commit/3ced1c0e30368dcb859a2720cc060310e2c57c6c)
