### ISSUE TITLE
[Bug] Infer from query object name not working

### ISSUE THREAD

**Issue by miyamotokenji** [neume/queryko#3]
```ruby
ProductsQuery.new(created_at_min: 'Jun 10, 2019')
```

From the example, results in.

> NoMethodError (undefined method `paginate' for {:created_at_max=>Mon, 10 Jun 2019 10:18:50 +0000}:Hash)

I am using Rails 5.1.6, Ruby 2.5.0

Thank you _gwapo_.

**Comment by neume** [comment]
There was bug in inferring the model class `Product` from the query object class name -- where in your case, it's `ProductsQuery`. Versions `v1.2.2` and `v2.0.0` were also affected by this bug

A workaround is overriding the `initialize` method with

```ruby
def initialize(options = {}, collection = Products.all)
  super(options, collection)
end
```
Version `v1.2.4` and `v2.0.2` fixes this bug. You can upgrade your gem to use this feature without the workaround

Closing the issue now. Feel free to reopen this if there are still issues regarding this
